// MCForm1 design code.
// setups up basic form design and controls

using System.Drawing.Printing;

namespace TwinCAT_ADS_MC;

partial class MCForm1
{

    public Label amsLabel;
    public Label localAMSLabel;
    public Label portLabel;
    public CheckBox port851CheckBox;
    public Label port851Label;
    public TextBox userAMSIDText;
    public TextBox userPortText;
    public CheckBox localCheckBox;
    public Label plcConnectedLabel;
    public Label axisConnectedLabel;
    public Button connectButton;

    public Label axesNumLabel;
    public TextBox axesNumText;
    public Button axisConnectButton;
    public Button axesSetupButton;

    public RadioButton moveAbsoluteRadio;
    public Label moveAbsoluteLabel;
    public RadioButton moveRelativeRadio;
    public Label moveRelativeLabel;
    public RadioButton moveHomeRadio;
    public Label moveHomeLabel;

    public Label setLabel;
    public Label readLabel;
    public Label positionLabel;
    public TextBox positionSetText;
    public TextBox positionActualText;
    public Label velocityLabel;
    public TextBox velocitySetText;
    public TextBox velocityActualText;
    
    public Button executeButton;

    private System.ComponentModel.IContainer components = null;

    /// <summary>
    ///  Clean up any resources being used.
    /// </summary>
    /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
    protected override void Dispose(bool disposing) // code that is auto-generated by winforms. don't touch!
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    private void InitializeComponent() // called by MCForm1 constructor
    {
        this.components = new System.ComponentModel.Container();
        this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        this.ClientSize = new System.Drawing.Size(500, 500); // define size of window
        this.Text = "TwinCAT-ADS-MC"; // define name of window

        FormDesignSetup(); // call the design setup function to create all the controls
    }

    private void FormDesignSetup()
    {
        System.Windows.Forms.Timer timer1 = new System.Windows.Forms.Timer(); // setup new timer for refreshing form data
        timer1.Interval=1000; // 1 second
        timer1.Tick += new EventHandler(timer1_Tick); // adding event handler for timer tick. located in MCForm1.EventHandler
        timer1.Start(); // start timer

        #region AMS Net ID
        // textbox and label for AMS net ID

        userAMSIDText = new TextBox(); // set position text box
        userAMSIDText.Size = new Size(125,20);
        userAMSIDText.Location = new Point(90,25);
        this.Controls.Add(userAMSIDText);

        amsLabel = new Label();
        amsLabel.Size = new Size(100,20);
        amsLabel.Location = new Point(10,30);
        amsLabel.Text = "AMS Net ID:";
        this.Controls.Add(amsLabel);

        # endregion

        #region Local checkbox
        // checkbox and label for selecting whether the PLC user connecting to is local or not
        // this read-onlys the AMS net ID as the event handler code will retrieve the local AMS net ID

        localCheckBox = new CheckBox(); // checkbox
        localCheckBox.Size = new Size(20,20);
        localCheckBox.Location = new Point(150,50);
        this.Controls.Add(localCheckBox);
        localCheckBox.Click += new EventHandler(localCheckBox_Click);

        localAMSLabel = new Label();
        localAMSLabel.Size = new Size(80,20);
        localAMSLabel.Location = new Point(100,52);
        localAMSLabel.Text = "Local?";
        this.Controls.Add(localAMSLabel);

        #endregion

        #region Port
        // textbox and label for PLC port number
        // to do: add checkbox for standard port 851?

        userPortText = new TextBox(); // set position text box
        userPortText.Size = new Size(75,20);
        userPortText.Location = new Point(275,25);
        this.Controls.Add(userPortText);

        portLabel = new Label();
        portLabel.Size = new Size(50,20);
        portLabel.Location = new Point(225,30);
        portLabel.Text = "Port:";
        this.Controls.Add(portLabel);

        #endregion

        #region port 851 checkbox

        port851CheckBox = new CheckBox(); // checkbox
        port851CheckBox.Size = new Size(20,20);
        port851CheckBox.Location = new Point(330,50);
        this.Controls.Add(port851CheckBox);
        port851CheckBox.Click += new EventHandler(port851CheckBox_Click);

        port851Label = new Label();
        port851Label.Size = new Size(80,20);
        port851Label.Location = new Point(275,50);
        port851Label.Text = "Port 851?";
        this.Controls.Add(port851Label);

        #endregion

        #region Connect button
        // button to connect to PLC

        connectButton = new Button(); // initiialise button
        connectButton.Size = new Size(75,40);
        connectButton.Location = new Point(375,17);
        connectButton.Text = "Connect";
        this.Controls.Add(connectButton);
        connectButton.Click += new EventHandler(connectButton_Click);

        #endregion

        #region Axes number
        // textbox and label for axis number

        axesNumLabel = new Label();
        axesNumLabel.Size = new Size(60,20);
        axesNumLabel.Location = new Point(70,120);
        axesNumLabel.Text = "Axes No.";
        this.Controls.Add(axesNumLabel);
        
        axesNumText = new TextBox();
        axesNumText.Size = new Size(50,30);
        axesNumText.Location = new Point(150,110);
        axesNumText.Font = new Font(FontFamily.GenericSansSerif, 16.0F, FontStyle.Bold);
        axesNumText.Text = "1";
        this.Controls.Add(axesNumText);

        #endregion

        #region Axes connect button
        // button for connecting to axis

        axisConnectButton = new Button();
        axisConnectButton.Size = new Size(75,40);
        axisConnectButton.Location = new Point(225,105);
        axisConnectButton.Text = "Connect to Axis";
        this.Controls.Add(axisConnectButton);
        axisConnectButton.Click += new EventHandler(axisConnectButton_Click);

        #endregion

        #region Axes setup button
        // button for opening new window to edit motion parameters

        axesSetupButton = new Button();
        axesSetupButton.Size = new Size(75,40);
        axesSetupButton.Location = new Point(350,105);
        axesSetupButton.Text = "Axes Setup";
        this.Controls.Add(axesSetupButton);
        axesSetupButton.Click += new EventHandler(axesSetupButton_Click);

        #endregion

        #region Set / Read Labels
        // labels for set and read textboxes 

        setLabel = new Label();
        setLabel.Size = new Size(100,20);
        setLabel.Location = new Point(175,225);
        setLabel.Text = "Set:";
        this.Controls.Add(setLabel);

        readLabel = new Label();
        readLabel.Size = new Size(100,20);
        readLabel.Location = new Point(325,225);
        readLabel.Text = "Actual:";
        this.Controls.Add(readLabel);

        #endregion

        #region Position
        // label, textbox for set data and textbox for actual data 

        positionLabel = new Label();
        positionLabel.Size = new Size(60,20);
        positionLabel.Location = new Point(20,250);
        positionLabel.Text = "Position:";
        this.Controls.Add(positionLabel);

        positionSetText = new TextBox(); // set position text box
        positionSetText.Size = new Size(100,50);
        positionSetText.Location = new Point(150,250);
        this.Controls.Add(positionSetText);

        positionActualText = new TextBox(); // actual read set position text box
        positionActualText.Size = new Size(125,50);
        positionActualText.Location = new Point(325,250);
        positionActualText.Font = new Font(FontFamily.GenericSansSerif, 10.0F, FontStyle.Italic);
        positionActualText.ReadOnly = true;
        this.Controls.Add(positionActualText);

        #endregion

        #region Velocity
        // label, textbox for set data and textbox for actual data 

        velocityLabel = new Label();
        velocityLabel.Size = new Size(60,20);
        velocityLabel.Location = new Point(20,300);
        velocityLabel.Text = "Velocity:";
        this.Controls.Add(velocityLabel);

        velocitySetText = new TextBox(); // set velocity text box
        velocitySetText.Size = new Size(100,50);
        velocitySetText.Location = new Point(150,300);
        this.Controls.Add(velocitySetText);

        velocityActualText = new TextBox(); // actual read velocity text box
        velocityActualText.Size = new Size(125,50);
        velocityActualText.Location = new Point(325,300);
        velocityActualText.Font = new Font(FontFamily.GenericSansSerif, 10.0F, FontStyle.Italic);
        velocityActualText.ReadOnly = true;
        this.Controls.Add(velocityActualText);

        #endregion

        #region Acceleration
        // currently not used. TODO?
        // label, textbox for set data and textbox for actual data 

        //accelerationLabel = new Label();
        //accelerationLabel.Size = new Size(80,20);
        //accelerationLabel.Location = new Point(20,350);
        //accelerationLabel.Text = "Acceleration:";
        //this.Controls.Add(accelerationLabel);

        //setAcclText = new TextBox(); // set position text box
        //setAcclText.Size = new Size(100,50);
        //setAcclText.Location = new Point(150,350);
        //this.Controls.Add(setAcclText);

        //readAcclText = new TextBox(); // actual read set position text box
        //readAcclText.Size = new Size(75,50);
        //readAcclText.Location = new Point(325,350);
        //readAcclText.Font = new Font(FontFamily.GenericSansSerif, 10.0F, FontStyle.Italic);
        //readAcclText.ReadOnly = true;
        //this.Controls.Add(readAcclText);

        #endregion

        #region Execute button
        // button that executes a move with values in set textboxes

        executeButton = new Button();
        executeButton.Size = new Size(75,40);
        executeButton.Location = new Point(175,400);
        executeButton.Text = "Execute Move";
        this.Controls.Add(executeButton);
        executeButton.Click += new EventHandler(executeButton_Click);

        #endregion

        #region move command type radio buttons

        // radio buttons that select which move type user wants: absolute, relative or home

        #region absolute

        moveAbsoluteRadio = new RadioButton();
        moveAbsoluteRadio.Size = new Size(20,20);
        moveAbsoluteRadio.Location = new Point(125,175);
        this.Controls.Add(moveAbsoluteRadio);
        moveAbsoluteRadio.Click += new EventHandler(moveAbsoluteRadio_Click);
        moveAbsoluteRadio.Checked = true; // intially checked when form opened

        moveAbsoluteLabel = new Label();
        moveAbsoluteLabel.Size = new Size(100,20);
        moveAbsoluteLabel.Location = new Point(35,175);
        moveAbsoluteLabel.Text = "Move Absolute:";
        this.Controls.Add(moveAbsoluteLabel);

        #endregion

        #region relative

        moveRelativeRadio = new RadioButton();
        moveRelativeRadio.Size = new Size(20,20);
        moveRelativeRadio.Location = new Point(275,175);
        this.Controls.Add(moveRelativeRadio);
        moveRelativeRadio.Click += new EventHandler(moveRelativeRadio_Click);

        moveRelativeLabel = new Label();
        moveRelativeLabel.Size = new Size(100,20);
        moveRelativeLabel.Location = new Point(185,175);
        moveRelativeLabel.Text = "Move Relative:";
        this.Controls.Add(moveRelativeLabel);

        #endregion

        #region home

        moveHomeRadio = new RadioButton();
        moveHomeRadio.Size = new Size(20,20);
        moveHomeRadio.Location = new Point(425,175);
        this.Controls.Add(moveHomeRadio);
        moveHomeRadio.Click += new EventHandler(moveHomeRadio_Click);

        moveHomeLabel = new Label();
        moveHomeLabel.Size = new Size(100,20);
        moveHomeLabel.Location = new Point(335,175);
        moveHomeLabel.Text = "Move Home:";
        this.Controls.Add(moveHomeLabel);

        #endregion

        #endregion

        #region Connected labels
        // labels below connect button and axis connect button
        // helps tell the user whether connection was successful
        
        plcConnectedLabel = new Label();
        plcConnectedLabel.Size = new Size(100,20);
        plcConnectedLabel.Location = new Point(375,60);
        plcConnectedLabel.Text = "Disconnected"; // intially set text as disconnected. this will be changed to connected only when PLC is connected
        plcConnectedLabel.Font = new Font(FontFamily.GenericSansSerif, 8.0F, FontStyle.Italic);
        this.Controls.Add(plcConnectedLabel);

        axisConnectedLabel = new Label();
        axisConnectedLabel.Size = new Size(100,20);
        axisConnectedLabel.Location = new Point(225,150);
        axisConnectedLabel.Text = "Disconnected"; // intially set text as disconnected. this will be changed to connected only when axis is connected
        axisConnectedLabel.Font = new Font(FontFamily.GenericSansSerif, 8.0F, FontStyle.Italic);
        this.Controls.Add(axisConnectedLabel);   


        #endregion

        CenterToScreen(); // centres the window on the screen
    }
}
